---
### The plays in this set will perform the monthly publishing of errata for content views
### This will automatically publish new versions to the Library. 
### Promotion to development will managed separately

- name: Refresh facts for all discovered hosts
  gather_facts: True 
  remote_user: root
  hosts: sat6.parmstrong.ca
  
  roles:
  - refreshdiscovery
