---
# This playbook implements the task of updating the rule for a content view
# and publishing the content view to Library

- name: Get the Content View Rule ID for the Content View
  command: "hammer --output=json content-view filter rule list --content-view-filter={{ content_view_filter }} --content-view={{ item.name }} --organization={{ organization }}"
  register: cmdOutput

- name: Pull the RuleID
  set_fact: cvf_rule_id={{ cmdOutput.stdout | from_json | json_query('[0]."Rule ID"') }}

- name: Get the new EndDate
  set_fact: end_date={{ ansible_date_time.date }}

- debug:
    msg: "Setting new date to {{ end_date }}" 

- name: Set the new EndDate for the errata window
  command: "hammer --output=json content-view filter rule update --id={{ cvf_rule_id }} --end-date={{ end_date }} --content-view-filter={{ content_view_filter }} --content-view={{ item.name }} --organization={{ organization }}"
  register: cmdOutput

- debug: 
    msg: "{{ cmdOutput.stdout }}"
